### ISSUE TITLE
npm peer dependencies warning

### ISSUE THREAD

**Issue by reactjser** [DamianOsipiuk/vue-query#59]
When I install `vue-query`, there is a warning that shows `npm WARN react-query@3.18.1 requires a peer of react@^16.8.0 || ^17.0.0 but none is installed. You must install peer dependencies yourself`.

**Comment by reactjser** [comment]
![image](https://user-images.githubusercontent.com/54932880/127378110-445fdd4a-5f39-4d96-a7ab-cc59bbdc30f2.png)
The type check also failed because I didn't install `react`.

**Comment by DamianOsipiuk** [comment]
@reactjser As for the warning, I think we cannot do anything about it, unfortunately, since we are relying on the `react-query` core.
Until `react-query` would be split into core and react packages that would be completely separate, we have to live with that.
Unless you have some clever trick to fix that warning. I would be keen to learn that :wink: 

As for the error... I could not reproduce it, so I might need some repro example.
But I think it might be connected to https://github.com/DamianOsipiuk/vue-query/issues/57 and connects to the fact that we have just reexported all types from `react-query/types`. Doing this more selectively may be a solution.

Could you also try https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.7.1 to double-check if this is an issue?

**Comment by DamianOsipiuk** [comment]
@reactjser Should be fixed in https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.8.1
Let me know if it works for you.

**Comment by reactjser** [comment]
v1.8.1 didn't fix type check. Here is a repo [https://github.com/reactjser/vue3](https://github.com/reactjser/vue3), run `npm i && npx vue-tsc`.

**Comment by DamianOsipiuk** [comment]
@reactjser Please check https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.8.3

**Comment by DamianOsipiuk** [comment]
@reactjser If the issue is not fixed, feel free to reopen

**Comment by ItMaga** [comment]
@DamianOsipiuk I have similar issue with type check and vue-demi exported member

![issue](https://user-images.githubusercontent.com/51162910/134888320-f9b81da8-ffe8-49dc-8c7c-9a6404fcbce1.png)

It can be fixed somehow or cannot do anything about it? I wouldn't like to resort to `skipLibCheck`)
